In [2]:
import pandas as pd

Raw data was loaded from API and saved in a previous notebook. Can reload that code here if needed.

Will redo first stage of cleaning here.

In [7]:
import pandas as pd
daily_stock_df = pd.read_csv('raw_daily_data/combined_daily_data.csv')
daily_stock_df['timestamp'] = pd.to_datetime(daily_stock_df['timestamp']).dt.date
daily_stock_df

,timestamp,ticker,open,high,low,close,volume,vwap,transactions
0,2021-05-05,A,132.090,134.090,131.25,133.37,1.447574e+06,133.1998,19877.0
1,2021-05-06,A,132.310,132.600,130.77,132.40,1.173755e+06,131.8933,20455.0
2,2021-05-07,A,133.190,134.820,133.19,133.90,1.056246e+06,133.9869,17352.0
3,2021-05-10,A,133.760,133.930,131.76,131.87,1.048008e+06,132.4934,22316.0
4,2021-05-11,A,130.270,131.840,129.30,131.42,1.356117e+06,131.1175,19161.0
...,...,...,...,...,...,...,...,...,...
4986763,2026-04-27,ZYME,27.930,29.750,27.93,28.56,9.502180e+05,28.8344,13412.0
4986764,2026-04-28,ZYME,28.610,28.885,27.92,27.94,4.214716e+05,28.1324,9773.0
4986765,2026-04-29,ZYME,27.520,27.950,26.77,27.83,8.244088e+05,27.7028,13249.0
4986766,2026-04-30,ZYME,27.975,28.185,27.18,27.54,4.826677e+05,27.5929,11679.0
4986767,2026-05-01,ZYME,27.540,27.540,26.61,26.61,3.701084e+05,26.8420,11490.0

In [8]:
daily_stock_df.dtypes

timestamp        object
ticker           object
open            float64
high            float64
low             float64
close           float64
volume          float64
vwap            float64
transactions    float64
dtype: object

In [9]:
fb_df = pd.read_csv('raw_daily_data/daily_fb.csv')
fb_df['timestamp'] = pd.to_datetime(fb_df['timestamp']).dt.date
fb_df

,timestamp,ticker,open,high,low,close,volume,vwap,transactions
0,2021-05-05,FB,318.1900,321.0600,314.4900,315.0200,1.557060e+07,317.3538,201397
1,2021-05-06,FB,314.5200,320.2400,313.2750,320.0200,1.901224e+07,317.5020,218059
2,2021-05-07,FB,322.3800,322.9350,318.7500,319.0800,1.591674e+07,320.4781,209827
3,2021-05-10,FB,314.3500,314.5786,304.8300,305.9700,2.423917e+07,307.8293,324498
4,2021-05-11,FB,300.7500,306.8400,299.6900,306.5300,1.892009e+07,303.8195,281399
...,...,...,...,...,...,...,...,...,...
486,2026-04-27,FB,43.6148,43.6148,43.6148,43.6148,2.639097e+01,43.6527,19
487,2026-04-28,FB,43.6090,43.6090,43.5697,43.5697,2.479427e+02,43.6032,16
488,2026-04-29,FB,43.5900,43.5900,43.5317,43.5317,1.769432e+02,43.5884,21
489,2026-04-30,FB,43.7301,43.7301,43.7301,43.7301,7.901293e+01,43.5953,17
490,2026-05-01,FB,43.9350,44.0100,43.7762,43.7762,1.919489e+03,43.9232,41

In [10]:
full_stock_df = pd.concat([daily_stock_df, fb_df], axis=0)


full_stock_df

,timestamp,ticker,open,high,low,close,volume,vwap,transactions
0,2021-05-05,A,132.0900,134.0900,131.2500,133.3700,1.447574e+06,133.1998,19877.0
1,2021-05-06,A,132.3100,132.6000,130.7700,132.4000,1.173755e+06,131.8933,20455.0
2,2021-05-07,A,133.1900,134.8200,133.1900,133.9000,1.056246e+06,133.9869,17352.0
3,2021-05-10,A,133.7600,133.9300,131.7600,131.8700,1.048008e+06,132.4934,22316.0
4,2021-05-11,A,130.2700,131.8400,129.3000,131.4200,1.356117e+06,131.1175,19161.0
...,...,...,...,...,...,...,...,...,...
486,2026-04-27,FB,43.6148,43.6148,43.6148,43.6148,2.639097e+01,43.6527,19.0
487,2026-04-28,FB,43.6090,43.6090,43.5697,43.5697,2.479427e+02,43.6032,16.0
488,2026-04-29,FB,43.5900,43.5900,43.5317,43.5317,1.769432e+02,43.5884,21.0
489,2026-04-30,FB,43.7301,43.7301,43.7301,43.7301,7.901293e+01,43.5953,17.0
490,2026-05-01,FB,43.9350,44.0100,43.7762,43.7762,1.919489e+03,43.9232,41.0

In [11]:
full_stock_df = pd.concat([daily_stock_df, fb_df], axis=0)
full_stock_df

# #full_stock_df['timestamp'] = pd.to_datetime(full_stock_df['timestamp']).dt.date

# df_metafb_fix = full_stock_df.copy()

# #df_metafb_fix["timestamp"] = pd.to_datetime(df_metafb_fix["timestamp"])

# df_metafb_fix

,timestamp,ticker,open,high,low,close,volume,vwap,transactions
0,2021-05-05,A,132.0900,134.0900,131.2500,133.3700,1.447574e+06,133.1998,19877.0
1,2021-05-06,A,132.3100,132.6000,130.7700,132.4000,1.173755e+06,131.8933,20455.0
2,2021-05-07,A,133.1900,134.8200,133.1900,133.9000,1.056246e+06,133.9869,17352.0
3,2021-05-10,A,133.7600,133.9300,131.7600,131.8700,1.048008e+06,132.4934,22316.0
4,2021-05-11,A,130.2700,131.8400,129.3000,131.4200,1.356117e+06,131.1175,19161.0
...,...,...,...,...,...,...,...,...,...
486,2026-04-27,FB,43.6148,43.6148,43.6148,43.6148,2.639097e+01,43.6527,19.0
487,2026-04-28,FB,43.6090,43.6090,43.5697,43.5697,2.479427e+02,43.6032,16.0
488,2026-04-29,FB,43.5900,43.5900,43.5317,43.5317,1.769432e+02,43.5884,21.0
489,2026-04-30,FB,43.7301,43.7301,43.7301,43.7301,7.901293e+01,43.5953,17.0
490,2026-05-01,FB,43.9350,44.0100,43.7762,43.7762,1.919489e+03,43.9232,41.0

In [13]:
cutoff_date = pd.to_datetime("2022-06-09").date()

# Keep FB through 2022-06-08
full_stock_df = full_stock_df[
    ~((full_stock_df["ticker"] == "FB") & (full_stock_df["timestamp"] >= cutoff_date))
]

# Keep META from 2022-06-09 onward
full_stock_df = full_stock_df[
    ~((full_stock_df["ticker"] == "META") & (full_stock_df["timestamp"] < cutoff_date))
]

full_stock_df["ticker"] = full_stock_df["ticker"].replace({"FB": "META"})

full_stock_df

,timestamp,ticker,open,high,low,close,volume,vwap,transactions
0,2021-05-05,A,132.09,134.090,131.25,133.37,1447574.0,133.1998,19877.0
1,2021-05-06,A,132.31,132.600,130.77,132.40,1173755.0,131.8933,20455.0
2,2021-05-07,A,133.19,134.820,133.19,133.90,1056246.0,133.9869,17352.0
3,2021-05-10,A,133.76,133.930,131.76,131.87,1048008.0,132.4934,22316.0
4,2021-05-11,A,130.27,131.840,129.30,131.42,1356117.0,131.1175,19161.0
...,...,...,...,...,...,...,...,...,...
272,2022-06-02,META,188.45,200.935,187.73,198.86,31951582.0,195.8094,336899.0
273,2022-06-03,META,195.98,196.610,189.78,190.78,19464993.0,192.0885,239486.0
274,2022-06-06,META,193.99,196.920,188.40,194.25,30574242.0,193.2857,307707.0
275,2022-06-07,META,191.93,196.530,191.49,195.65,18628687.0,194.4583,204288.0
276,2022-06-08,META,194.67,202.030,194.41,196.64,22267154.0,198.3613,247919.0

There should no longer be any FB data.

In [15]:
full_stock_df[full_stock_df['ticker'] == 'FB']

Empty DataFrame
Columns: [timestamp, ticker, open, high, low, close, volume, vwap, transactions]
Index: []

META should go back to the beginning of the dataset.

In [16]:
full_stock_df[full_stock_df['ticker'] == 'META']

,timestamp,ticker,open,high,low,close,volume,vwap,transactions
2851154,2022-06-09,META,194.28,199.450,183.6800,184.00,23501579.0,190.7486,282457.0
2851155,2022-06-10,META,183.04,183.100,175.0200,175.57,27478354.0,177.3336,366773.0
2851156,2022-06-13,META,170.59,172.575,164.0300,164.26,31749304.0,167.2440,440307.0
2851157,2022-06-14,META,166.03,166.750,161.3601,163.73,27192049.0,163.7958,341928.0
2851158,2022-06-15,META,167.20,172.160,163.9750,169.35,29808251.0,167.5321,340902.0
...,...,...,...,...,...,...,...,...,...
272,2022-06-02,META,188.45,200.935,187.7300,198.86,31951582.0,195.8094,336899.0
273,2022-06-03,META,195.98,196.610,189.7800,190.78,19464993.0,192.0885,239486.0
274,2022-06-06,META,193.99,196.920,188.4000,194.25,30574242.0,193.2857,307707.0
275,2022-06-07,META,191.93,196.530,191.4900,195.65,18628687.0,194.4583,204288.0
276,2022-06-08,META,194.67,202.030,194.4100,196.64,22267154.0,198.3613,247919.0

Just need to re-sort.

In [17]:
full_stock_df = full_stock_df.sort_values(by=['ticker', 'timestamp'])

Now it should be in order.

In [18]:
full_stock_df[full_stock_df['ticker'] == 'META']

,timestamp,ticker,open,high,low,close,volume,vwap,transactions
0,2021-05-05,META,318.190,321.0600,314.4900,315.020,1.557060e+07,317.3538,201397.0
1,2021-05-06,META,314.520,320.2400,313.2750,320.020,1.901224e+07,317.5020,218059.0
2,2021-05-07,META,322.380,322.9350,318.7500,319.080,1.591674e+07,320.4781,209827.0
3,2021-05-10,META,314.350,314.5786,304.8300,305.970,2.423917e+07,307.8293,324498.0
4,2021-05-11,META,300.750,306.8400,299.6900,306.530,1.892009e+07,303.8195,281399.0
...,...,...,...,...,...,...,...,...,...
2852126,2026-04-27,META,670.995,682.5000,670.8400,678.620,1.274664e+07,677.2405,336701.0
2852127,2026-04-28,META,674.240,678.1800,665.6250,671.340,1.060559e+07,671.0503,323398.0
2852128,2026-04-29,META,668.910,674.2500,663.8084,669.120,1.904737e+07,658.9351,570557.0
2852129,2026-04-30,META,619.320,620.8500,600.0000,611.910,5.276516e+07,609.3627,1505192.0
2852130,2026-05-01,META,614.690,618.8800,606.1100,608.745,2.140403e+07,611.5610,589201.0

Success!

In [19]:
full_stock_df

,timestamp,ticker,open,high,low,close,volume,vwap,transactions
0,2021-05-05,A,132.09,134.090,131.2500,133.370,1.447574e+06,133.1998,19877.0
1,2021-05-06,A,132.31,132.600,130.7700,132.400,1.173755e+06,131.8933,20455.0
2,2021-05-07,A,133.19,134.820,133.1900,133.900,1.056246e+06,133.9869,17352.0
3,2021-05-10,A,133.76,133.930,131.7600,131.870,1.048008e+06,132.4934,22316.0
4,2021-05-11,A,130.27,131.840,129.3000,131.420,1.356117e+06,131.1175,19161.0
...,...,...,...,...,...,...,...,...,...
3035378,2026-04-27,NaN,2.29,2.290,1.8500,1.850,9.317473e+04,2.1023,1094.0
3035379,2026-04-28,NaN,2.01,2.110,1.7800,1.795,2.693652e+05,1.9115,1846.0
3035380,2026-04-29,NaN,1.86,1.860,1.6000,1.605,1.364121e+05,1.6963,1155.0
3035381,2026-04-30,NaN,1.60,1.850,1.5801,1.770,1.013014e+05,1.6733,858.0
3035382,2026-05-01,NaN,1.79,2.005,1.7900,1.810,8.277586e+04,1.8830,746.0

In [20]:
full_stock_df.to_csv('transformed_daily_data/Cleaned_New_2026_05_18.csv', index=False)