Won't be doing much in this notebook, just quick glances and tests.

In [13]:
# import pandas as pd

# with open("COMMAND_load_merge_transform.txt", "r") as file:
#     code = file.read()
#     exec(code)

In [1]:
import pandas as pd

In [5]:
df = pd.read_parquet('oversize_datasets/daily_cleaned_price_data.parquet')
df

,timestamp,ticker,open,high,low,close,volume,vwap,transactions
0,2021-05-24,A,133.51,134.41,132.5300,133.34,1.325305e+06,133.6936,18683.0
1,2021-05-25,A,133.41,134.80,133.0100,133.23,1.905708e+06,133.6992,26967.0
2,2021-05-26,A,136.30,138.00,133.2505,133.29,2.530998e+06,134.5671,31259.0
3,2021-05-27,A,133.32,138.14,133.1600,137.54,3.720923e+06,137.2590,37177.0
4,2021-05-28,A,138.60,139.21,138.0001,138.13,1.289049e+06,138.4188,20108.0
...,...,...,...,...,...,...,...,...,...
3493827,2026-05-15,ZYME,24.50,25.34,23.6346,23.93,6.407959e+05,23.8908,11366.0
3493828,2026-05-18,ZYME,23.93,24.70,23.8800,24.43,7.502414e+05,24.3372,14709.0
3493829,2026-05-19,ZYME,24.19,24.55,23.8700,24.40,6.153201e+05,24.3494,12503.0
3493830,2026-05-20,ZYME,24.40,25.20,24.2650,24.84,5.426638e+05,24.8734,13051.0
3493831,2026-05-21,ZYME,24.42,25.36,24.3700,25.11,6.186212e+05,25.0966,11303.0

In [7]:
df2 = pd.read_parquet('daily_cleaned_metadata.parquet')
df2

,ticker,name,market_cap,exchange,country
0,A,Agilent Technologies Inc.,3.215449e+10,XNYS,us
1,AA,Alcoa Corporation,1.692590e+10,XNYS,us
2,AAL,American Airlines Group Inc.,8.564938e+09,XNAS,us
3,AAOI,"Applied Optoelectronics, Inc.",1.326092e+10,XNAS,us
4,AAON,Aaon Inc,1.095651e+10,XNAS,us
...,...,...,...,...,...
2779,ZNTL,"Zentalis Pharmaceuticals, Inc. Common Stock",2.641014e+08,XNAS,us
2780,ZS,"Zscaler, Inc. Common Stock",2.804994e+10,XNAS,us
2781,ZTS,ZOETIS INC.,3.341667e+10,XNYS,us
2782,ZUMZ,Zumiez Inc.,3.930853e+08,XNAS,us
2783,ZYME,Zymeworks Inc.,1.827577e+09,XNAS,us

In [8]:
df3 = pd.merge(df, df2, on="ticker")
df3

,timestamp,ticker,open,high,low,close,volume,vwap,transactions,name,market_cap,exchange,country
0,2021-05-24,A,133.51,134.41,132.5300,133.34,1.325305e+06,133.6936,18683.0,Agilent Technologies Inc.,3.215449e+10,XNYS,us
1,2021-05-25,A,133.41,134.80,133.0100,133.23,1.905708e+06,133.6992,26967.0,Agilent Technologies Inc.,3.215449e+10,XNYS,us
2,2021-05-26,A,136.30,138.00,133.2505,133.29,2.530998e+06,134.5671,31259.0,Agilent Technologies Inc.,3.215449e+10,XNYS,us
3,2021-05-27,A,133.32,138.14,133.1600,137.54,3.720923e+06,137.2590,37177.0,Agilent Technologies Inc.,3.215449e+10,XNYS,us
4,2021-05-28,A,138.60,139.21,138.0001,138.13,1.289049e+06,138.4188,20108.0,Agilent Technologies Inc.,3.215449e+10,XNYS,us
...,...,...,...,...,...,...,...,...,...,...,...,...,...
3493827,2026-05-15,ZYME,24.50,25.34,23.6346,23.93,6.407959e+05,23.8908,11366.0,Zymeworks Inc.,1.827577e+09,XNAS,us
3493828,2026-05-18,ZYME,23.93,24.70,23.8800,24.43,7.502414e+05,24.3372,14709.0,Zymeworks Inc.,1.827577e+09,XNAS,us
3493829,2026-05-19,ZYME,24.19,24.55,23.8700,24.40,6.153201e+05,24.3494,12503.0,Zymeworks Inc.,1.827577e+09,XNAS,us
3493830,2026-05-20,ZYME,24.40,25.20,24.2650,24.84,5.426638e+05,24.8734,13051.0,Zymeworks Inc.,1.827577e+09,XNAS,us
3493831,2026-05-21,ZYME,24.42,25.36,24.3700,25.11,6.186212e+05,25.0966,11303.0,Zymeworks Inc.,1.827577e+09,XNAS,us

In [9]:
# Unique to list
all_stocks = df3['ticker'].unique().tolist()

In [10]:
with open('list_all_stocks.txt', 'w') as file:
    for item in all_stocks:
        file.write(f"{item}\n")  # Adds a newline character after each item

In [13]:
sp500_tickers = [
    'MMM', 'AOS', 'ABT', 'ABBV', 'ACN', 'ADBE', 'AMD', 'AES', 'AFL', 'A',
    'APD', 'ABNB', 'AKAM', 'ALB', 'ARE', 'ALGN', 'ALLE', 'LNT', 'ALL', 'GOOGL',
    'GOOG', 'MO', 'AMZN', 'AMCR', 'AEE', 'AEP', 'AXP', 'AIG', 'AMT', 'AWK',
    'AMP', 'AME', 'AMGN', 'APH', 'ADI', 'AON', 'APA', 'APO', 'AAPL', 'AMAT',
    'APP', 'APTV', 'ACGL', 'ADM', 'ARES', 'ANET', 'AJG', 'AIZ', 'T', 'ATO',
    'ADSK', 'ADP', 'AZO', 'AVY', 'AXON', 'BKR', 'BAC', 'BAX', 'BDX', 'BRK.B',
    'BBY', 'TECH', 'BLK', 'BX', 'BA', 'BKNG', 'BSX', 'BMY', 'AVGO', 'BR',
    'BRO', 'BF.B', 'BLDR', 'BG', 'BXP', 'CHRW', 'CDNS', 'CPT', 'COF', 'CAH',
    'CCL', 'CARR', 'CVNA', 'CASY', 'CAT', 'CBRE', 'CDW', 'CNC', 'CNP', 'CF',
    'CRL', 'SCHW', 'CHTR', 'CVX', 'CMG', 'CB', 'CHD', 'CIEN', 'CI', 'CINF',
    'CTAS', 'CSCO', 'C', 'CFG', 'CLX', 'CME', 'CMS', 'KO', 'CTSH', 'COIN',
    'CL', 'CMCSA', 'FIX', 'COP', 'ED', 'STZ', 'COO', 'CPRT', 'GLW', 'CTVA',
    'CSGP', 'COST', 'CRH', 'CRWD', 'CCI', 'CSX', 'CMI', 'CVS', 'DHR', 'DRI',
    'DDOG', 'DVA', 'DECK', 'DE', 'DELL', 'DAL', 'DVN', 'DXCM', 'FANG', 'DLR',
    'DG', 'DLTR', 'D', 'DPZ', 'DASH', 'DOV', 'DOW', 'DHI', 'DTE', 'DUK',
    'DD', 'ETN', 'EBAY', 'ECL', 'EIX', 'EW', 'EME', 'EMR', 'ETR', 'EOG',
    'EQT', 'EFX', 'EQIX', 'ERIE', 'ESS', 'EL', 'EVRG', 'ES', 'EXC', 'EXPE',
    'EXPD', 'EXR', 'XOM', 'FFIV', 'FDS', 'FICO', 'FAST', 'FRT', 'FDX', 'FERG',
    'FIS', 'FITB', 'FSLR', 'FE', 'FLEX', 'F', 'FTNT', 'FTV', 'FOXA', 'FOX',
    'BEN', 'FCX', 'GRMN', 'IT', 'GE', 'GNRC', 'GD', 'GIS', 'GM', 'GPC',
    'GILD', 'GPN', 'GL', 'GDDY', 'GS', 'HAL', 'HIG', 'HAS', 'HCA', 'HSIC',
    'HSY', 'HPE', 'HLT', 'HD', 'HON', 'HRL', 'HST', 'HWM', 'HPQ', 'HUBB',
    'HUM', 'HBAN', 'HII', 'IBM', 'IEX', 'IDXX', 'ITW', 'INCY', 'IR', 'PODD',
    'INTC', 'IBKR', 'ICE', 'IFF', 'IP', 'INTU', 'ISRG', 'IVZ', 'INVH', 'IQV',
    'IRM', 'JBHT', 'JBL', 'JKHY', 'J', 'JNJ', 'JCI', 'JPM', 'KDP', 'KEY',
    'KEYS', 'KMB', 'KIM', 'KMI', 'KKR', 'KLAC', 'KHC', 'KR', 'LHX', 'LH',
    'LRCX', 'LVS', 'LDOS', 'LEN', 'LII', 'LLY', 'LIN', 'LYV', 'LMT', 'L',
    'LOW', 'LULU', 'LITE', 'LYB', 'MTB', 'MPC', 'MAR', 'MLM', 'MRVL', 'MAS',
    'MA', 'MKC', 'MCD', 'MCK', 'MDT', 'MRK', 'META', 'MET', 'MTD', 'MGM',
    'MCHP', 'MU', 'MSFT', 'MAA', 'MRNA', 'TAP', 'MDLZ', 'MPWR', 'MNST', 'MCO',
    'MS', 'MOS', 'MSI', 'MSCI', 'NDAQ', 'NTAP', 'NFLX', 'NEM', 'NWSA', 'NWS',
    'NEE', 'NKE', 'NI', 'NDSN', 'NSC', 'NTRS', 'NOC', 'NCLH', 'NRG', 'NUE',
    'NVDA', 'NVR', 'NXPI', 'ORLY', 'OXY', 'ODFL', 'OMC', 'ON', 'OKE', 'ORCL',
    'OTIS', 'PCAR', 'PKG', 'PLTR', 'PANW', 'PH', 'PAYX', 'PYPL', 'PNR', 'PEP',
    'PFE', 'PCG', 'PM', 'PSX', 'PNW', 'PNC', 'PPG', 'PPL', 'PFG', 'PG',
    'PGR', 'PLD', 'PRU', 'PEG', 'PTC', 'PSA', 'PHM', 'PWR', 'QCOM', 'DGX',
    'RL', 'RJF', 'RTX', 'O', 'REG', 'REGN', 'RF', 'RSG', 'RMD', 'ROK',
    'ROL', 'ROP', 'ROST', 'RCL', 'SPGI', 'CRM', 'SBAC', 'SLB', 'STX', 'SRE',
    'NOW', 'SHW', 'SPG', 'SWKS', 'SJM', 'SNA', 'SO', 'LUV', 'SWK', 'SBUX',
    'STT', 'STLD', 'STE', 'SYK', 'SMCI', 'SYF', 'SNPS', 'SYY', 'TMUS', 'TROW',
    'TTWO', 'TPR', 'TRGP', 'TGT', 'TEL', 'TDY', 'TER', 'TSLA', 'TXN', 'TPL',
    'TXT', 'TMO', 'TJX', 'TTD', 'TSCO', 'TT', 'TDG', 'TRV', 'TRMB', 'TFC',
    'TYL', 'TSN', 'USB', 'UBER', 'UDR', 'ULTA', 'UNP', 'UAL', 'UPS', 'URI',
    'UNH', 'UHS', 'VLO', 'VEEV', 'VTR', 'VRSN', 'VRSK', 'VZ', 'VRTX', 'VRT',
    'VTRS', 'VICI', 'V', 'VST', 'VMC', 'WRB', 'GWW', 'WAB', 'WMT', 'DIS',
    'WM', 'WAT', 'WEC', 'WFC', 'WELL', 'WST', 'WDC', 'WY', 'WSM', 'WMB',
    'WDAY', 'WYNN', 'XEL', 'XYL', 'YUM', 'ZBRA', 'ZBH', 'ZTS'
]


with open('list_sp500.txt', 'w') as file:
    for item in sp500_tickers:
        file.write(f"{item}\n")  # Adds a newline character after each item

In [ ]:
feature_set_2 = only_3_df['feature'].unique().tolist()

In [ ]:
with open('feature_set_2.txt', 'w') as file:
    for item in feature_set_2:
        file.write(f"{item}\n")  # Adds a newline character after each item

In [17]:
sp500_df = df3[
    df3['ticker'].isin(sp500_tickers)
].copy()

sp500_df

,timestamp,ticker,open,high,low,close,volume,vwap,transactions,name,market_cap,exchange,country
0,2021-05-24,A,133.51,134.410,132.5300,133.34,1.325305e+06,133.6936,18683.0,Agilent Technologies Inc.,3.215449e+10,XNYS,us
1,2021-05-25,A,133.41,134.800,133.0100,133.23,1.905708e+06,133.6992,26967.0,Agilent Technologies Inc.,3.215449e+10,XNYS,us
2,2021-05-26,A,136.30,138.000,133.2505,133.29,2.530998e+06,134.5671,31259.0,Agilent Technologies Inc.,3.215449e+10,XNYS,us
3,2021-05-27,A,133.32,138.140,133.1600,137.54,3.720923e+06,137.2590,37177.0,Agilent Technologies Inc.,3.215449e+10,XNYS,us
4,2021-05-28,A,138.60,139.210,138.0001,138.13,1.289049e+06,138.4188,20108.0,Agilent Technologies Inc.,3.215449e+10,XNYS,us
...,...,...,...,...,...,...,...,...,...,...,...,...,...
3491317,2026-05-15,ZTS,75.40,76.900,72.3800,74.22,8.951993e+06,74.5755,87728.0,ZOETIS INC.,3.341667e+10,XNYS,us
3491318,2026-05-18,ZTS,74.20,77.955,74.2000,77.72,8.848290e+06,77.0103,94191.0,ZOETIS INC.,3.341667e+10,XNYS,us
3491319,2026-05-19,ZTS,79.85,80.360,77.5930,78.92,7.296778e+06,79.0676,89147.0,ZOETIS INC.,3.341667e+10,XNYS,us
3491320,2026-05-20,ZTS,78.47,80.435,77.2500,79.71,7.404723e+06,79.4831,72544.0,ZOETIS INC.,3.341667e+10,XNYS,us
3491321,2026-05-21,ZTS,78.99,80.420,76.2122,80.07,8.562458e+06,79.1743,87554.0,ZOETIS INC.,3.341667e+10,XNYS,us

In [23]:
sp500_df['close_pct_of_day1'] = sp500_df.groupby('ticker')['close'].transform(lambda x: (x / x.iloc[0]) * 100)
sp500_df

,timestamp,ticker,open,high,low,close,volume,vwap,transactions,name,market_cap,exchange,country,close_pct_of_day1
0,2021-05-24,A,133.51,134.410,132.5300,133.34,1.325305e+06,133.6936,18683.0,Agilent Technologies Inc.,3.215449e+10,XNYS,us,100.000000
1,2021-05-25,A,133.41,134.800,133.0100,133.23,1.905708e+06,133.6992,26967.0,Agilent Technologies Inc.,3.215449e+10,XNYS,us,99.917504
2,2021-05-26,A,136.30,138.000,133.2505,133.29,2.530998e+06,134.5671,31259.0,Agilent Technologies Inc.,3.215449e+10,XNYS,us,99.962502
3,2021-05-27,A,133.32,138.140,133.1600,137.54,3.720923e+06,137.2590,37177.0,Agilent Technologies Inc.,3.215449e+10,XNYS,us,103.149843
4,2021-05-28,A,138.60,139.210,138.0001,138.13,1.289049e+06,138.4188,20108.0,Agilent Technologies Inc.,3.215449e+10,XNYS,us,103.592320
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3491317,2026-05-15,ZTS,75.40,76.900,72.3800,74.22,8.951993e+06,74.5755,87728.0,ZOETIS INC.,3.341667e+10,XNYS,us,42.074830
3491318,2026-05-18,ZTS,74.20,77.955,74.2000,77.72,8.848290e+06,77.0103,94191.0,ZOETIS INC.,3.341667e+10,XNYS,us,44.058957
3491319,2026-05-19,ZTS,79.85,80.360,77.5930,78.92,7.296778e+06,79.0676,89147.0,ZOETIS INC.,3.341667e+10,XNYS,us,44.739229
3491320,2026-05-20,ZTS,78.47,80.435,77.2500,79.71,7.404723e+06,79.4831,72544.0,ZOETIS INC.,3.341667e+10,XNYS,us,45.187075
3491321,2026-05-21,ZTS,78.99,80.420,76.2122,80.07,8.562458e+06,79.1743,87554.0,ZOETIS INC.,3.341667e+10,XNYS,us,45.391156

In [25]:
sp500_metadata = sp500_df[['timestamp', 'ticker', 'name']]

In [26]:
sp500_close_data = sp500_df[['timestamp', 'ticker', 'name', 'close']]

In [27]:
sp500_metadata.to_parquet('S&P_500_Metadata.parquet', index=False)

In [28]:
sp500_close_data.to_parquet('S&P_500_Price_data.parquet', index=False)

In [11]:
df4 = df3[['timestamp', 'ticker', 'name', 'close']]
df4

          timestamp ticker                       name   close
0        2021-05-24      A  Agilent Technologies Inc.  133.34
1        2021-05-25      A  Agilent Technologies Inc.  133.23
2        2021-05-26      A  Agilent Technologies Inc.  133.29
3        2021-05-27      A  Agilent Technologies Inc.  137.54
4        2021-05-28      A  Agilent Technologies Inc.  138.13
...             ...    ...                        ...     ...
3493827  2026-05-15   ZYME             Zymeworks Inc.   23.93
3493828  2026-05-18   ZYME             Zymeworks Inc.   24.43
3493829  2026-05-19   ZYME             Zymeworks Inc.   24.40
3493830  2026-05-20   ZYME             Zymeworks Inc.   24.84
3493831  2026-05-21   ZYME             Zymeworks Inc.   25.11

[3493832 rows x 4 columns]

In [12]:
df4.to_parquet('daily_cleaned_price_data_CLOSE.parquet', index=False)

# /#

In [18]:
import pandas as pd

df = pd.read_csv('daily_cleaned_price_data.csv')

df2 = pd.read_csv('daily_cleaned_metadata.csv')

df3 = pd.merge(df, df2, on="ticker")

In [19]:
df3['close_pct_of_day1'] = (df3.groupby('ticker')['close'].transform(lambda x: (x / x.iloc[0]) * 100))
df3

,timestamp,ticker,open,high,low,close,volume,vwap,transactions,name,market_cap,exchange,country,close_pct_of_day1
0,2021-05-24,A,133.51,134.41,132.5300,133.34,1.325305e+06,133.6936,18683.0,Agilent Technologies Inc.,3.215449e+10,XNYS,us,100.000000
1,2021-05-25,A,133.41,134.80,133.0100,133.23,1.905708e+06,133.6992,26967.0,Agilent Technologies Inc.,3.215449e+10,XNYS,us,99.917504
2,2021-05-26,A,136.30,138.00,133.2505,133.29,2.530998e+06,134.5671,31259.0,Agilent Technologies Inc.,3.215449e+10,XNYS,us,99.962502
3,2021-05-27,A,133.32,138.14,133.1600,137.54,3.720923e+06,137.2590,37177.0,Agilent Technologies Inc.,3.215449e+10,XNYS,us,103.149843
4,2021-05-28,A,138.60,139.21,138.0001,138.13,1.289049e+06,138.4188,20108.0,Agilent Technologies Inc.,3.215449e+10,XNYS,us,103.592320
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3493827,2026-05-15,ZYME,24.50,25.34,23.6346,23.93,6.407959e+05,23.8908,11366.0,Zymeworks Inc.,1.827577e+09,XNAS,us,82.975035
3493828,2026-05-18,ZYME,23.93,24.70,23.8800,24.43,7.502414e+05,24.3372,14709.0,Zymeworks Inc.,1.827577e+09,XNAS,us,84.708738
3493829,2026-05-19,ZYME,24.19,24.55,23.8700,24.40,6.153201e+05,24.3494,12503.0,Zymeworks Inc.,1.827577e+09,XNAS,us,84.604716
3493830,2026-05-20,ZYME,24.40,25.20,24.2650,24.84,5.426638e+05,24.8734,13051.0,Zymeworks Inc.,1.827577e+09,XNAS,us,86.130374
3493831,2026-05-21,ZYME,24.42,25.36,24.3700,25.11,6.186212e+05,25.0966,11303.0,Zymeworks Inc.,1.827577e+09,XNAS,us,87.066574

In [20]:
df4 = df3[['timestamp', 'ticker', 'name', 'close', 'close_pct_of_day1']]
df4

,timestamp,ticker,name,close,close_pct_of_day1
0,2021-05-24,A,Agilent Technologies Inc.,133.34,100.000000
1,2021-05-25,A,Agilent Technologies Inc.,133.23,99.917504
2,2021-05-26,A,Agilent Technologies Inc.,133.29,99.962502
3,2021-05-27,A,Agilent Technologies Inc.,137.54,103.149843
4,2021-05-28,A,Agilent Technologies Inc.,138.13,103.592320
...,...,...,...,...,...
3493827,2026-05-15,ZYME,Zymeworks Inc.,23.93,82.975035
3493828,2026-05-18,ZYME,Zymeworks Inc.,24.43,84.708738
3493829,2026-05-19,ZYME,Zymeworks Inc.,24.40,84.604716
3493830,2026-05-20,ZYME,Zymeworks Inc.,24.84,86.130374
3493831,2026-05-21,ZYME,Zymeworks Inc.,25.11,87.066574

In [22]:
df4['close_pct_of_day1'] = df4['close_pct_of_day1'].round(2)

/var/folders/cf/4zrkk0lx1nbdx9tpklpk4jc00000gn/T/ipykernel_57786/3964713187.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df4['close_pct_of_day1'] = df4['close_pct_of_day1'].round(2)

In [24]:
df4.to_parquet('daily_cleaned_price_data.parquet', index=False)

In [25]:
testload = pd.read_parquet('daily_cleaned_price_data.parquet')

In [28]:
price_df = pd.read_csv('daily_cleaned_price_data.csv')
price_df.to_parquet('daily_cleaned_price_data.parquet')

In [29]:
metadata_df = pd.read_csv('daily_cleaned_metadata.csv')
metadata_df.to_parquet('daily_cleaned_metadata.parquet')